Added name
browserstack/intern-browserstack pull request #22
Opened 2023-06-26 05:30 UTC by agarneha1331

2023-06-29 09:00 UTC, karanshah-browserstack requested changes

2023-06-29 09:00 UTC, karanshah-browserstack commented on intern.json
> +    "name": "BStack intern snippet",
Bstack sample test

2023-07-05 06:25 UTC, agarneha1331 commented on intern.json
> +    "name": "BStack intern snippet",
changed

2023-07-06 07:03 UTC, karanshah-browserstack approved these changes

2023-07-07 11:19 UTC, merged